# Site settings
title: Samuel Chinedu | My Portfolio
description: About my software developer journey
baseurl: "/" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Samuel Chinedu
user_description: Hey, welcome to my page. My name is Samuel; I'm a software developer. I love programming in C++ and Python, I have worked with other awesome tools like Qt, Unity 3D and Linux OS. On this page I show some projects I have developed for learning and for fun. I build applications that I need or tools that help me learn one valuable skill or another. I'd love to hear your thoughts on them.
user_title: Software Developer
email: mrwhistler316@gmail.com
twitter_username: eltroy316
github_username:  delivite
gplus_username:  mrwhistler316

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
